FROM python:3.6-slim-stretch
RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential

# Copy app source.
WORKDIR /app/streamlistener
COPY . .

# Install requirements.
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-test.txt

# Start command.
CMD ["mypy", "--ignore-missing-imports", "main.py"]
