apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-listener
  labels:
    app: stream-listener
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: stream-listener
        image: eu.gcr.io/mimir-185212/stream-listener:4.0-DEV
        env:
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: consumerKey
              name: twitter-api-credentials
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: consumerSecret
              name: twitter-api-credentials
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: accessToken
              name: twitter-api-credentials
        - name: TWITTER_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: accessSecret
              name: twitter-api-credentials
        - name: DIRECTORY_URL
          value: http://directory:8080
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - test
            - '`find /tmp/stream-listener-health.txt -mmin 1`'
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command:
            - test
            - '`find /tmp/stream-listener-health.txt -mmin 1`'
          initialDelaySeconds: 20
        resources: {}
      imagePullSecrets:
      - name: gcr-json-key